### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by ochin08** [BlackTechX011/Hacx-GPT#1]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Hacx-GPT/Hacx.py", line 1, in <module>
    import requests, os, random
ModuleNotFoundError: No module named 'requests'

**Comment by BlackTechX011** [comment]
okay i will try to fix

**Comment by BlackTechX011** [comment]
type this in Termux
```
pkg update && pkg upgrade
```
```
pkg install python3
```
```
pkg install git
```
```
pip install requests 
```
 - if it don't work try
 ```
pkg install requests
```
