### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ochin08** [BlackTechX011/Hacx-GPT#4]
Error: 'choices'                                                                        
E :  {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}

Hacx:  None

**Comment by BlackTechX011** [comment]
___
Your API key is no longer valid. To continue using our services, please upgrade to an OpenAI premium account or create a new account with a different email and phone number.
___
