### ISSUE TITLE
Isnt at all like darkweb gpt

### ISSUE THREAD

**Issue by Hiroshi0Nohara** [BlackTechX011/Hacx-GPT#6]
i tried asking him questions related creating a mallicious python script , it didnt responded saying the same stuff sorry i cant provide you with that info, i cxant assist you with that request and so on, i mean it was so simple even anyone whom i have given a custom made prompt have generated me a python malware that grabs computer's username, external ip address, and google chrome cookies, zip everything and send to a Telegram webhook. but it was unable to do it. 

please correct it otherwise its just a same gpt working in a termux and nothing else.

**Comment by BlackTechX011** [comment]
okay, I understand your issue this is because it use chatGPT as AI so sometime it happens try by staring your question by "write a python script" like this it should work  if not than i try to find something

**Comment by Hiroshi0Nohara** [comment]
Well , i was doing the same , but on your saying i tried it again , it still didn't happened.

**Comment by BlackTechX011** [comment]
# Hello @Hiroshi0Nohara 👋
i am working on it and new version are coming very soon
