### ISSUE TITLE
GPT 3.5?

### ISSUE THREAD

**Issue by t0fum4n** [BlackTechX011/Hacx-GPT#9]
Not a hater... But you definitely need to be more clear on what this is. 

This is just a fancy system prompt and a call to OpenAI... And not even the good model.

**Comment by t0fum4n** [comment]
I 100% agree with you. But what you are representing this as, is not what it is. It's an API wrapper with a fancy system prompt.... Nothing more. Neat. For sure. Good job on it. But you need to be clear with users on what this actually is. 

I've built tools just like this. One for fishing. One for Bitcoin price data. One for writing tweets. But none of them use any unique or foundational components. Just off the shelf libraries and APIs. 

Now, if you would take a suggestion. Package this with Ollama and instruct users on how to implement that. They even have a pypi package to make it easy. 

Again. Not hating... Just making sure things are properly represented.

**Comment by BlackTechX011** [comment]
That's a nice idea! I'm already planning to add more modes. However, there's an issue with Ollama that it requires significant compute power and a GPU, which not everyone has access to, including myself. I rely on the cloud for these tasks, and this poses a challenge for implementing local models.
